### DISCUSSION TITLE
Template for use with PowerClub

### DISCUSSION THREAD

**Discussion by kineticscreen** [davewatson91/hass-amber-electric#6] [Show and tell]
For those that are on PowerClub, rather than Amber, but want to use the live pricing data, this template sensor converts the price into the form compatible with how it's displayed in the PowerClub app:

```
sensors:
  current_power_price:
    friendly_name: "Current Power Price"
    unit_of_measurement: "$/kWh"
    value_template: "{{ (states('sensor.amber_general_usage_price')|float / 110 - 0.1|float)|round(2) }}"
```

![image](https://user-images.githubusercontent.com/39250334/121621151-f21c6700-caae-11eb-8b2b-51dd0a348185.png)
![image](https://user-images.githubusercontent.com/39250334/121621189-06f8fa80-caaf-11eb-9719-04a4723b5faa.png)
